name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gdrive]  # or dvc[all], depending on your remote

      - name: Run pipeline with DVC
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}   # ✅ This is crucial
        run: |
          echo "DAGSHUB_PAT=$DAGSHUB_PAT"
          dvc repro
